services:
  - type: web
    name: e-osews
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app.main:app
    envVars:
      - key: EOSEWS_API_TOKEN
        generateValue: true
